"""creation url entity

Revision ID: 0172f174d5a9
Revises: 
Create Date: 2022-10-15 18:22:43.234622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0172f174d5a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_shortener',
    sa.Column('id_url', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('long_url', sa.String(), nullable=False),
    sa.Column('hash_url', sa.String(), nullable=False),
    sa.Column('status_url', sa.Enum('active', 'inactive', name='status'), nullable=False),
    sa.Column('total_access', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id_url'),
    sa.UniqueConstraint('long_url')
    )
    op.create_index(op.f('ix_url_shortener_id_url'), 'url_shortener', ['id_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_shortener_id_url'), table_name='url_shortener')
    op.drop_table('url_shortener')
    # ### end Alembic commands ###
