"""settings model url entity

Revision ID: 4fdfe14b2d08
Revises: dd1ea57ea0dc
Create Date: 2022-10-13 21:59:37.311409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fdfe14b2d08'
down_revision = 'dd1ea57ea0dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_shortener', sa.Column('total_access', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url_shortener', 'total_access')
    # ### end Alembic commands ###
