"""new entity url

Revision ID: a04dbe368774
Revises: 
Create Date: 2022-10-16 21:00:04.435333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a04dbe368774'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_shortener',
    sa.Column('id_url', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('long_url', sa.String(length=255), nullable=True),
    sa.Column('short_url', sa.String(length=255), nullable=True),
    sa.Column('id_hash', sa.Integer(), nullable=True),
    sa.Column('hash_url', sa.String(length=255), nullable=True),
    sa.Column('status_url', sa.Enum('active', 'inactive', name='statusenum'), nullable=True),
    sa.Column('total_access', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id_url'),
    sa.UniqueConstraint('hash_url'),
    sa.UniqueConstraint('id_hash'),
    sa.UniqueConstraint('long_url'),
    sa.UniqueConstraint('short_url')
    )
    op.create_index(op.f('ix_url_shortener_id_url'), 'url_shortener', ['id_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_shortener_id_url'), table_name='url_shortener')
    op.drop_table('url_shortener')
    # ### end Alembic commands ###
